### Example getting a token using a Walkfares client
@tenantid=ef34dc37-9d55-43c4-99ad-a35f3c96f8f4
@appid=39c6cccd-d6ea-4ac1-b564-8e4d1e28d75d
@secret=4T4V_nK288jIiyIh1eSO5tQ0Yk-~6LC..u
@scope=api://opendatadsl/.default

GET /{{tenantid}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{appid}}&
client_secret={{secret}}&
scope={{scope}}

### Example getting a token using customer tenant and client app
@client_appid=61bfc625-5cb3-462e-b2fd-1bffd24e18ed
@client_tenantid=9fbf6424-eafa-4bdc-bd40-6008c3fdb934
@client_secret=g4-2Y45l69w0wRl5~fEMo6w6.bQEupDpx-

GET /{{client_tenantid}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{client_appid}}&
client_secret={{client_secret}}&
scope={{scope}}
