@token={{auth.response.body.access_token}}

### Log into AAD
# @name auth

GET /{{tenantId}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{clientId}}&
client_secret={{secret}}&
scope=api://opendatadsl/.default

### Update a curve
POST {{url}}/object/v1
Authorization: Bearer {{token}}
x-odsl-environment: odsl54

{
    "_id" : "NZ_FONTERRA_SALTED_25KG_NZ",
    "_type" : "#ForwardCurve",
    "_links" : {},
    "_access": "#F1",
    "CURVE" : {
        "_id" : "CURVE",
        "_type" : "VarCurve",
        "created" : "2020-11-10T07:38:20.400205",
        "ondate" : {
            "curveDate" : "2000-07-09",
            "expiryCalendar" : "EOMBUSINESS"
        },
        "currency" : "USD",
        "units" : "MT",
        "contracts" : [ 
            {
                "tenor" : "M01",
                "value" : 3835,
                "ondate" : {
                    "curveDate" : "2000-07-11",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2020M12",
                    "end" : "2020-12-31T00:00:00",
                    "expiry" : "2020-11-30T00:00:00",
                    "relative" : "M01",
                    "start" : "2020-12-01T00:00:00"
                }
            }, 
            {
                "tenor" : "M02",
                "value" : 3845,
                "ondate" : {
                    "curveDate" : "2020-11-03",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2021M01",
                    "end" : "2021-01-31T00:00:00",
                    "expiry" : "2020-12-31T00:00:00",
                    "relative" : "M02",
                    "start" : "2021-01-01T00:00:00"
                }
            }, 
            {
                "tenor" : "M03",
                "value" : 3815,
                "ondate" : {
                    "curveDate" : "2020-11-03",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2021M02",
                    "end" : "2021-02-28T00:00:00",
                    "expiry" : "2021-01-29T00:00:00",
                    "relative" : "M03",
                    "start" : "2021-02-01T00:00:00"
                }
            }, 
            {
                "tenor" : "M04",
                "value" : 3805,
                "ondate" : {
                    "curveDate" : "2020-11-03",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2021M03",
                    "end" : "2021-03-31T00:00:00",
                    "expiry" : "2021-02-26T00:00:00",
                    "relative" : "M04",
                    "start" : "2021-03-01T00:00:00"
                }
            }, 
            {
                "tenor" : "M05",
                "value" : "NaN",
                "ondate" : {
                    "curveDate" : "2020-11-03",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2021M04",
                    "end" : "2021-04-30T00:00:00",
                    "expiry" : "2021-03-31T00:00:00",
                    "relative" : "M05",
                    "start" : "2021-04-01T00:00:00"
                }
            }, 
            {
                "tenor" : "M06",
                "value" : "NaN",
                "ondate" : {
                    "curveDate" : "2020-11-03",
                    "expiryCalendar" : "EOMBUSINESS"
                },
                "properties" : {
                    "absolute" : "2021M05",
                    "end" : "2021-05-31T00:00:00",
                    "expiry" : "2021-04-30T00:00:00",
                    "relative" : "M06",
                    "start" : "2021-05-01T00:00:00"
                }
            }
        ],
        "properties" : {
            "event" : "271.00"
        }
    },
    "category" : "Agriculture",
    "class" : "FUTURE",
    "collection" : "F1",
    "contracts" : [],
    "currency" : "USD",
    "description" : "Global Dairy Trade: Butter",
    "location" : "NZ",
    "name" : "Global Dairy Trade: Butter Fonterra Salted 25kg NZ",
    "product" : "GDT_BUTTER",
    "source" : "Global Dairy Trade",
    "tags" : [ 
        "AGS", 
        "BUTTER", 
        "NZ", 
        "GDT"
    ],
    "units" : "MT"
}