@token={{auth.response.body.access_token}}

### Log into AAD
# @name auth

GET /{{tenantId}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{clientId}}&
client_secret={{secret}}&
scope=api://opendatadsl/.default

### Send a message
POST {{url}}/rt/send/rs/TEST
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "message": "Hello World"
}