@token={{auth.response.body.access_token}}

### Log into AAD
# @name auth

GET /{{tenantId}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{clientId}}&
client_secret={{secret}}&
scope=api://opendatadsl/.default

### Dynamic
GET {{url}}/data/v1/all/TEST%3aCLOSE%3a2022-04-07
    ?expression=BASE*1.05
    &script=%23CurveScript
Authorization: Bearer {{token}}

### Dynamic Help
GET {{url}}/data/v1/all/TEST%3aCLOSE%3a2022-04-07
    ?expression=BASE*1.05
    &script=%23CurveScript
    &_function=help
Authorization: Bearer {{token}}

###
{{url}}/data/v1/public
    ?_filter={"_type":{"$in":["VarTimeSeries","VarSmartTimeSeries","VarCurveDates","VarSmartCurve"]}}
    &_project={"data":false,"properties":false,"contracts":false,"ondate":false,"_tag":false}&_sort={"_id":1}
    &_limit=1000
    &_skip=0
Authorization: Bearer {{token}}
