@token={{auth.response.body.access_token}}

### Log into AAD
# @name auth

GET /{{tenantId}}/oauth2/v2.0/token
Host: login.microsoftonline.com
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials&
client_id={{clientId}}&
client_secret={{secret}}&
scope=api://opendatadsl/.default

### Create view
POST {{url}}/process-exec/v1/private
Authorization: Bearer {{token}}

{
    "_id": "test_view",
    "_type": "view",
    "_view": "[{\"$group\":{\"_id\":\"$status\",\"count\":{\"$sum\":1}}}]"
}